# Generated by Django 4.2.28 on 2026-03-03 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('aqi', models.IntegerField(verbose_name='AQI level 1-5')),
                ('co', models.FloatField(verbose_name='CO μg/m³')),
                ('no2', models.FloatField(verbose_name='NO₂ μg/m³')),
                ('o3', models.FloatField(verbose_name='O₃ μg/m³')),
                ('pm2_5', models.FloatField(verbose_name='PM2.5 μg/m³')),
                ('pm10', models.FloatField(verbose_name='PM10 μg/m³')),
                ('so2', models.FloatField(verbose_name='SO₂ μg/m³')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aqi_readings', to='locations.location')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('temp', models.FloatField(verbose_name='Temperature')),
                ('feels_like', models.FloatField(verbose_name='Feels like')),
                ('temp_min', models.FloatField(verbose_name='Min temperature')),
                ('temp_max', models.FloatField(verbose_name='Max temperature')),
                ('rain_1h', models.FloatField(default=0, verbose_name='Rain 1h (mm)')),
                ('snow_1h', models.FloatField(default=0, verbose_name='Snow 1h (mm)')),
                ('precip_prob', models.FloatField(default=0, verbose_name='Precipitation probability 0-1')),
                ('wind_speed', models.FloatField(verbose_name='Wind speed')),
                ('wind_direction', models.IntegerField(verbose_name='Wind direction (°)')),
                ('wind_gust', models.FloatField(default=0, verbose_name='Wind gust')),
                ('humidity', models.IntegerField(verbose_name='Humidity %')),
                ('dew_point', models.FloatField(null=True, verbose_name='Dew point')),
                ('pressure', models.FloatField(verbose_name='Pressure hPa')),
                ('visibility', models.IntegerField(default=10000, verbose_name='Visibility (m)')),
                ('uv_index', models.FloatField(default=0, verbose_name='UV Index')),
                ('cloud_cover', models.IntegerField(default=0, verbose_name='Cloud cover %')),
                ('weather_code', models.IntegerField(verbose_name='OWM weather code')),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=20)),
                ('sunrise', models.DateTimeField(null=True)),
                ('sunset', models.DateTimeField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='locations.location')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['location', 'recorded_at'], name='weather_wea_locatio_41141c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SevereWeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('extreme', 'Extreme')], default='moderate', max_length=20)),
                ('description', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='locations.location')),
            ],
            options={
                'ordering': ['-start'],
                'indexes': [models.Index(fields=['location', 'is_active', 'notified'], name='weather_sev_locatio_3100b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(db_index=True)),
                ('temp', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('wind_gust', models.FloatField(default=0)),
                ('rain_1h', models.FloatField(default=0)),
                ('snow_1h', models.FloatField(default=0)),
                ('rain_prob', models.FloatField(default=0)),
                ('uv_index', models.FloatField(default=0)),
                ('weather_code', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_forecasts', to='locations.location')),
            ],
            options={
                'ordering': ['dt'],
                'unique_together': {('location', 'dt')},
            },
        ),
        migrations.CreateModel(
            name='ForecastDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(db_index=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('temp_day', models.FloatField()),
                ('temp_night', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('feels_like_day', models.FloatField()),
                ('rain_prob', models.FloatField(default=0)),
                ('rain_amount', models.FloatField(default=0)),
                ('snow_amount', models.FloatField(default=0)),
                ('wind_speed', models.FloatField()),
                ('wind_gust', models.FloatField(default=0)),
                ('wind_direction', models.IntegerField()),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('dew_point', models.FloatField(null=True)),
                ('uv_index', models.FloatField(default=0)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('weather_code', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=20)),
                ('sunrise', models.DateTimeField(blank=True, null=True)),
                ('sunset', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_forecasts', to='locations.location')),
            ],
            options={
                'ordering': ['forecast_date'],
                'unique_together': {('location', 'forecast_date')},
            },
        ),
    ]
